name: OptEconomy
version: @version@
api-version: 1.13
main: com.github.playernguyen.OptEconomy
description: The powerful economy plugin for your Bukkit server.
commands:
  opteconomy:
    description: The OptEconomy plugin command
    usage: /points <sub-command>
    aliases: [ points, p ]